#include "libraries.h"

#ifndef _GEO_H
#define _GEO_H

/*MÓDULO DESTINADO À LEITURA DO ARQUIVO .GEO E ARMAZENAMENTO DE PARÂMETROS NO BANCO DE DADOS*/

//FUNÇÃO DE LEITURA E ARMAZENAMENTO DE PARÂMETROS DO ARQUIVO .GEO
void* getGeoParameters(void* paths);

#endif